title: Reality-Loop
description: Blog of Jonas Bandi

url: http://blog.jonasbandi.net
baseurl: ""
paginate_path: "blog/page:num/"
#permalink: blog/:title/
permalink: /:year/:month/:title.html

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
# - title: About
#   url: /about
# - title: Contact
#   url: /contact

social:
   github: jbandi
   twitter: jbandi
   facebook: jonasbandi
   email: jonas.bandi@ivorycode.com

google_analytics: "UA-3374180-2"

post_default_thumbnail: https://c2.staticflickr.com/2/1676/25736260092_310aaebf12_q.jpg
post_default_image: https://farm2.staticflickr.com/1676/25736260092_310aaebf12_z.jpg