title: Reality-Loop
description: Blog of Jonas Bandi

url: http://blog.jonasbandi.net/
baseurl: ""
paginate_path: "blog/page:num/"
#permalink: blog/:title/
permalink: /:year/:month/:title.html

markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
# - title: About
#   url: /about
# - title: Contact
#   url: /contact

social:
   github: jbandi
   twitter: jbandi
   facebook: jonasbandi
   email: jonas.bandi@ivorycode.com

google_analytics: "UA-3374180-2"